### ISSUE TITLE
Unexpected *args and **kwargs behaviour

### ISSUE THREAD

**Issue by biern** [QQuick/Transcrypt#102] opened 2016-08-21 09:44 UTC
Hi, thanks for sharing this project. I'm trying it out and have stumbled upon a few issues related to `*args` and `**kwargs`:

Calling JS method with *args passess `null` context to `apply`

``` javascript
        function Example() {};
        Example.prototype.foo = function () { console.log(this, arguments); };

        var example = new Example();
        example.foo(1, 2, 3);
        // Works as expected:
        // Object {  } Arguments { , 5 more… }
```

``` python
args = [1, 2, 3]
example = __new__(window.Example())
example.foo(*args)
# is transcribed to example.foo.call(null, args), "foo" context is lost:
# Window Arguments { , 5 more… }
example.foo(1, 2, 3)
# Object {  } Arguments { , 5 more… }
```

Unexpected `**kwargs` behaviour:

``` python
def some_function(foo, bar=None):
    print(foo, bar)

some_function('foo', bar='bar')
# prints: foo, null

def other_function(foo, bar='default', qaz='default'):
    print(foo, bar, qaz)

other_function('foo', qaz='qaz')
# prints: foo, default, default
```

I've tested this behaviour on .207 and master

**Comment by JdeH** [comment] 2016-08-21 11:41
Hi Marcin,

I accidentally closed this one somehow, sorry...
This issue requires a fix and some explanation.
Will get back to you.

Thanks for the feedback!!

**Comment by JdeH** [comment] 2016-08-21 13:46
Hi Marcin

Since keyword args are expensive in JS, you have to switch them on, preferably locally, at function definition (rather than call) time.

You also can use command line switch -k at compilation time, but this is disadvised, see docs.

```
__pragma__ ('kwargs')

def some_function(foo, bar=None):
    print(foo, bar)

some_function('foo', bar='bar')
# prints: foo, null

def other_function(foo, bar='default', qaz='default'):
    print(foo, bar, qaz)

other_function('foo', qaz='qaz')
# prints: foo, default, default

__pragma__ ('nokwargs')
```

As far as *args is concerned: Using a pure JS method with *args wasn't possible in JS 5, since it didn't have the spread operator. But it is possible in JS 6, so I've added that functionality. If you compile for JS 6 (-e 6 switch) it should work from commit ca3e038.

I've added a test for this to the transcrypt_only manual_tests, and committed that as well.

Kind regards
Jacques

PS Let me know if this all works for you.
PS2 You don't need es6 to run es6, the minifier will currently convert to es5, even with the es6 switch on. What this means it that you can use the -e 6 switch on any browser that can run es5. You still can do sourcelevel debuggin on the minified code using sourcemaps.

**Comment by biern** [comment] 2016-08-21 14:35
Hi Jacques, thanks for the rapid response.

As of `**kwargs`, it seems that I haven't done my homework reading the docs thoroughly :)
Compiling for es6 spread operator seems like a good idea and will definitely do the job for me.

Thanks again for helping me out.

**Comment by boxed** [comment] 2017-02-03 12:13
This is another case of the transcrypt compiler not giving an error on code it doesn't support and instead creates broken code. I'm fighting this problem with kwargs right now. 

I'm starting to feel that the design of transcrypt has to be fundamentally broken, because this type of thing has happened to me a LOT now. It's fine to not support stuff, but silently failing in hard to debug ways isn't fine.

**Comment by JdeH** [comment] 2017-02-03 12:53
Many things  in Transcrypt are under command line switches or pragma's. Kwargs is one such thing. The reason that these things are optional is that the code they generate with current JS facilities is bulky. With JS supporting more and more of those Python-like things, the need for switches will diminish.

But then there indeed is the question of reporting. The problem here is that support of kwargs requires inclusion of a mechanism at definition time, whereas the problem becomes manifest at call time, so at different, unpredictable locations. So an error message could only be generated at runtime requiring some kind of run time mechanism, which  would add overhead.

One way to tackle this is start from the opposite direction: Compile in the 'luxury' mode (with all Python compat switches on) and then switch off those facilities you don't use.

All in all there's a compromise here.
As for the design being "fundamentally broken", that would mean design decisions were taken that lead us the wrong way. Compared to other Py to JS compilers I don't think that's the case.  Transcrypt is somewhere in the spectrum between fast on one hand and complete on the other. Starting out with a small sane subset Transcrypt now support most constructs, but indeed some optional. Keeping it lean has been an important objective. An implementation like PyPyJs is very complete (by design) but also unbearabley (and as I fear irrepairably, unless browser manufacturers cooperate) slow. And things like Brython are somewhere inbetween. So which one to use depends on the job. And of course there's Typescript.

People using Trancrypt a long time in practice generally are quite shappy with it. But then again they know the limitations. I  think the error reporting can certainly be improved, it didn't have much priority until now. I've created a special label for this, so that these cases can be considered together.

**Comment by boxed** [comment] 2017-02-05 19:33
Yea, ok, "fundamentally broken" was bad phrasing on my part. I take it back. But it seems like unsupported stuff almost never results in an error message or a crash, but instead in invalid generated code. That's maybe a flaw in how you take a lot of small decisions.

For example, the bug what `@=` became `None=` suggests something like:

```python
ops = {
   '*': '*',
   '/': '/',
}
js_op = ops.get(python_op)
```

...and then not checking for None. Crashing is much better than producing invalid output silently.

**Comment by JdeH** [comment] 2017-02-05 20:32
It's certainly important to have proper error reports.
While improvements are certainly possible (and will happen), the code may be more systematic than you anticipate (and looks a bit like you propose):

```

        self.operators = {
            # Highest precendence

            ast.Not: ('!', 16),
            ast.Invert: ('~', 16),
            ast.UAdd: ('+', 16),
            ast.USub: ('-', 16),

            ast.Pow: (None, 15),        # Dealt with separately

            ast.Mult: ('*', 14),
            ast.MatMult: (None, 14),    # Dealt with separately
            ast.Div: ('/', 14),
            ast.FloorDiv: (None, 14),   # Dealt with separately
            ast.Mod: ('%', 14),         # Used only for JavaScript %, which differs from Python %

            ast.Add: ('+', 13),
            ast.Sub: ('-', 13),

            ast.LShift: ('<<', 12),
            ast.RShift: ('>>', 12),

            ast.Lt: ('<', 11),
            ast.LtE: ('<=', 11),
            ast.Gt: ('>', 11),
            ast.GtE: ('>=', 11),
            ast.In: (None, 11),         # Dealt with separately
            ast.NotIn: (None, 11),      # Dealt with separately

            ast.Eq: ('==', 10),
            ast.NotEq: ('!=', 10),
            ast.Is: ('===', 10),        # Not really, but closest for now
            ast.IsNot: ('!==', 10),     # Not really, but closest for now

            ast.BitAnd: ('&', 9),
            ast.BitOr: ('|', 8),
            ast.BitXor: ('^', 7),
            ast.And: ('&&', 6),
            ast.Or: ('||', 5)

            # Lowest precedence
        }

```

```
   def visit_BinOp (self, node):
        if type (node.op) == ast.FloorDiv:
            self.emit ('Math.floor (')
            self.visitSubExpr (node, node.left)
            self.emit (' / ')
            self.visitSubExpr (node, node.right)
            self.emit (')')
        elif (
            type (node.op) in (ast.Pow, ast.MatMult) or
            (type (node.op) == ast.Mod and (self.allowOperatorOverloading or not self.allowJavaScriptMod)) or
            (type (node.op) in (
                ast.Mult, ast.Div, ast.Add, ast.Sub,
                ast.LShift, ast.RShift, ast.BitOr, ast.BitXor, ast.BitAnd
            ) and self.allowOperatorOverloading)
        ):
            self.emit ('{} ('.format (self.filterId (
                # Non-overloaded
                ('__pow__' if self.allowOperatorOverloading else 'Math.pow') if type (node.op) == ast.Pow else
                '__matmul__' if type (node.op) == ast.MatMult else
                ('__jsmod__' if self.allowJavaScriptMod else '__mod__') if type (node.op) == ast.Mod else
                
                # Overloaded arithmetic
                '__mul__' if type (node.op) == ast.Mult else
                '__div__' if type (node.op) == ast.Div else
                '__add__' if type (node.op) == ast.Add else
                '__sub__' if type (node.op) == ast.Sub else
                
                # Overloaded bitwise
                '__lshift__' if type (node.op) == ast.LShift else
                '__rshift__' if type (node.op) == ast.RShift else
                '__or__' if type (node.op) == ast.BitOr else
                '__xor__' if type (node.op) == ast.BitXor else
                '__and__' if type (node.op) == ast.BitAnd else
                
                'Never here'
            )))
            self.visit (node.left)
            self.emit (', ')
            self.visit (node.right)
            self.emit (')')
        else:
            self.visitSubExpr (node, node.left)
            self.emit (' {} '.format (self.operators [type (node.op)][0]))
            self.visitSubExpr (node, node.right)
```

However optional operator overloading and things like array slices for numpy greatly complicate matters. I try to find a balance between adding features and regularly reorganizing the code.

**Closed** 2017-12-17 14:24 UTC
Labels: IS: enhancement, IS: improve comp. report

**Comment by emin63** [comment] 2019-01-01 14:30
I like transcrypt a lot but would like to chime in on suggesting crashing, raising an exception, or at least emitting a warning for unsupported behavior (e.g., *args or **kwargs). I don't have a problem with transcrypt making design decisions not to support things for efficiency reasons, but it's painful to stumble upon these.

Thanks for your great work.
