### ISSUE TITLE
Experimenting with transcrypt quickly pollutes git status

### ISSUE THREAD

**Issue by all3fox** [QQuick/Transcrypt#342] opened 2017-06-24 08:38 UTC
When one tries out different `examples` and `demos` that Transcrypt so generously provides, the `git status` command quickly picks up a lot of noise. Maybe a stricter `.gitignore` is to be used? See screenshot:

![screenshot from 2017-06-24 10-33-14](https://user-images.githubusercontent.com/962850/27507126-271b715a-58c9-11e7-971b-266da8e8c78e.png)

**Comment by the1337guy** [comment] 2017-06-24 12:03
I'm of the opinion that .gitignore should also contain __javascript__/ because it's reproducible.

**Comment by all3fox** [comment] 2017-06-24 13:17
@the1337guy well, as far as I can tell, not that much. When you introduce a new `transcrypt/modules`, you are given an option to implement it in javascript, right? For example, see `modules/maths`, there is a `__javascript__` directory there. It is probably autogenerated but I am not sure. Anyway, it is under `git`, so I assume it is not autogenerated.

Bottomline, looks like sometimes `__javascript__` is an important directory to include under source control, so it probably should not be globally `.gitignore`'ed

**Comment by the1337guy** [comment] 2017-06-24 13:18
Hmm, then it'd be hard to have rules that ONLY cover the autogenerated JS files.

**Comment by all3fox** [comment] 2017-06-24 13:25
No, it wouldn't. Just add 'em as you see 'em, like I am doing here: https://github.com/QQuick/Transcrypt/pull/345

**Comment by Michael-F-Ellis** [comment] 2017-06-24 14:50
My projects are attempting to be pure Python including re-running Transcrypt when source files change, so I've added
```
# directories created by Transcrypt
###################################
__javascript__/
```
to my own repos' .gitignore.

**Comment by JdeH** [comment] 2017-06-25 10:38
#345 merged.

Most JS files are autogenerated, but indeed not all.
If there's a .py file with the same name one directory level higher, they mostly are.

**Closed by JdeH** 2017-06-25 10:38 UTC
