### ISSUE TITLE
Support PEP 526 -- Syntax for Variable Annotations

### ISSUE THREAD

**Issue by sebnozzi** [QQuick/Transcrypt#280] opened 2017-02-04 16:05 UTC
Currently this code:
```
x: int = 3
```
gets compiled to this:
```
xint3;
```
PEP 526 is here: https://www.python.org/dev/peps/pep-0526/

**Comment by JdeH** [comment] 2017-02-04 16:15
Wow, that's bad.
Will repair, thanks!

BTW. The newest version of mypy will be bundled as soon as it's out, since it will contain an improved version of the API that will connect it to Transcrypt.

http://mypy.readthedocs.io/en/latest/command_line.html#integrating-mypy-into-another-python-application

The original API was found too intrusive by Guido, so it was replaced by this simple one.

https://github.com/python/mypy/pull/2744

As soon as this is released, Transcrypt will be adapted to use it, and with that the newest version of mypy with proper var annotation support.

Kind regards
Jacques

**Comment by sebnozzi** [comment] 2017-02-04 16:37
@JdeH Wow, thanks for the mega-quick response.

I am "new" to Python. That's why I went straight to the latest: 3.6.0.
My Transcrypt version is: 3.6.8 (installed via Pip).

As far as my little experiments go, I can confirm that mypy (0.470) also has problems with type-annotations in variables (it reports a parse error). The Python interpreter itself (the 3.6 version) of course has no issue. And the syntax also supported by the latest PyCharm.

Regarding your label: IS:bug? Well... I don't know. The 3.6 Python interpreter supports it, and you claim to be a 3.6 to JS compiler, so ... ;-) --- But if you are basing this on mypy the problem seems to be there.

mypy also does not support f-strings / PEP-498 (which Trascrypt does).

**Comment by sebnozzi** [comment] 2017-02-04 16:41
I also want to take the opportunity to thank you and all who make this project possible! :-)

As a web developer with a background in statically-typed languages and a fondness to whatever-to-JavaScript compilers the existence of this Python 3.6 (with optional type annotations) to JavaScript is enormously appreciated.

**Comment by JdeH** [comment] 2017-02-04 17:05
The  questionmark behind is:bug? isn't meant to express doubt that failing to generate code for `x: int = 3` is a bug, it clearly **is** a bug. It only means that' we haven't yet reproduced it (since we didn't try, that is). So it's just a stage in our quality assessment pipeline.

About the statically typed languages: I have been programming in C++ from its birth, and before that in Pascal and Algol 60, so the added value of compile time typechecks is clear to me.

Of course dynamic typing has also big advantages (flexibility, brief code), but especially when working with a team, static typechecks on module boundaries can save lots of trouble.

I hope you enjoy Trancrypt, and your bug reports are very welcome.

Kind regards
Jacques

**Comment by JdeH** [comment] 2017-02-04 18:59
Committed an experimental fix for this to GitHub (but not yet on PyPi.)
Feel free to reopen if there are still problems.

Annotation-support for 3.6 is still incomplete.
Will get priority as soon as next version of mypy is released.

**Closed by JdeH** 2017-02-04 18:59 UTC
Labels: IS: bug?, SUB: core

**Comment by sebnozzi** [comment] 2017-02-04 21:49
Thanks! For my purposes, it would be enough.

However, take into account that PEP-526 states that declaring the type of a variable **without** an assignment is also possible. What for? In the case of loops, for example. 

This is also possible, and currently not supported:
```
i: int
for i in range(0,5):
    print(i)
```
Or:
```
sane_world: bool
if 2+2 == 4:
    sane_world = True
else:
    sane_world = False
```
As I said, I don't use this - and can gladly wait for mypy to be updated. Just wanted to point it out.

**Comment by JdeH** [comment] 2017-02-05 10:34
I've committed a fix for the "var annotation without assignment" case.
