### ISSUE TITLE
set1_one_by_one list is broken

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#176] opened 2016-11-16 17:28 UTC
Hi, 

I just pulled master and tried to run the `run set1_one_by_one` script and it complains about not being able to find "transcrypt/div_fixes". This stalls the run script and does not allow it to proceed futher. I'm on git hash 92f0c0.

**Comment by JdeH** [comment] 2016-11-16 18:25
Oops, transcryt/div_fixes has been renamed to transcrypt/div_issues (fixes + enhancements)
This problem will be gone once we have one central testlet list, rather than a copy in the CI test.
But that has to await the problem with the math module accuracy (working on that).

**Comment by AXGKl** [comment] 2016-11-17 00:18
Hi, I commented it out in a new PR: https://github.com/QQuick/Transcrypt/pull/179

@RCL-Carl : The testsets (except set1 which is for travis) are anyway just examples which you should customize to your needs (i.e. where you work at, e.g. re otherwise you wait too long while developing). 


Here is a video about using the new dev mode: https://www.youtube.com/watch?v=lvTjKWVOwXA

**Comment by JdeH** [comment] 2016-11-17 09:47
@AXGKl 

Hi, great video!
I'll link to it from the doc page of the website.

@RCL-Carl 

I think I can close this now. If not, please reopen!

**Closed by JdeH** 2016-11-17 09:47 UTC

**Comment by AXGKl** [comment] 2016-11-19 11:17
video was intended mostly for @RCL-Carl so show the demo server.
Don't think its really good for transcrypt as the first one found in youtube, first impression should be different, far more polished. Also its outdated already, with @RCL-Carl's improvements on the .html.

=> I actually wanted to delete it again but if you like it I leave it and try to do a more polished one when I have time.

**Comment by JdeH** [comment] 2016-11-19 11:36
It's up to you.
A polished video would be great but I lack the skills for that.
Since you wanted to delete it I'll for now remove the link.

**Comment by AXGKl** [comment] 2016-11-19 12:33
lets do like this: you delete the link so that no body thinks its a transcrypt 'official' thing. and I add a note to the video that this just an informal heads up.

**Comment by JdeH** [comment] 2016-11-19 12:38
Agreed, link is deleted
