### ISSUE TITLE
How to use `zip()` on custom iterable?

### ISSUE THREAD

**Issue by theodox** [QQuick/Transcrypt#326] opened 2017-05-16 07:52 UTC
It looks like transcrypt expects a  `map()` method on custom iterables to make them work with zip().  If I just implement something like this:

``` 
class Vector:
     def __init__(self, *val):
         self.values = val

     def __add__(self, other):
        return Vector(*(a + b for a, b in zip(self, other)))
   
    def __iter__ (self):
       for item in self.values:
            yield item
```
and try something like 

```
Vector(1,2) + Vector(3,4)
```
or 

``` result = zip(Vector(1.2), Vector(3,4))
```

It will fail with `shortest.map is not a function`.    What would have to be implemented for this to work?

**Comment by withrocks** [comment] 2017-05-20 13:58
I'm experiencing the same problem without explicitly using zip.

I'm using Python's `enumerate`, which is under the hood implemented as a call to `zip`.

**Comment by withrocks** [comment] 2017-05-20 21:10
The issue I was having seems to have had to do with zipping a list of integers (or something else) with a string as the second argument, e.g. when calling `enumerate('abc')`.

I believe I've fixed it for my particular case, I'm not sure that it fixes the issue @theodox had, since I ran into another error when trying to reproduce that.

PR: https://github.com/QQuick/Transcrypt/pull/327.

**Comment by withrocks** [comment] 2017-06-03 14:32
@theodox: The pull request has been merged. It would be interesting to know if the patch solved your issue too.

**Comment by JdeH** [comment] 2017-06-10 17:16
@theodox 

The zip function has not yet been made suitable for the use of iterators.

As a workaround the following solution could be used here:

```
class Vector:
    def __init__(self, *val):
        self.values = val

    def __add__(self, other):
        return Vector(*(a + b for a, b in zip(self.values, other.values)))
            
__pragma__ ('opov')
v = Vector(1,2) + Vector(3,4)
__pragma__ ('noopov')

print (*v.values)   

```

BTW as you already may know,  iterators in general require the `-e 6 `switch

**Comment by JdeH** [comment] 2017-09-02 16:39
This will stay a workaround for the foreseeable future...

**Closed by JdeH** 2017-09-02 16:39 UTC
Labels: IS: workaround
