### ISSUE TITLE
-jc error

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#464] opened 2018-01-30 14:52 UTC
Hi,

Transpiled error since 3.6.86+ : self is null (whatever Python source) 

**self.interpreter_name = 'python';**

```
		'org.transcrypt.__base__', {
			__all__: {
				__inited__: false,
				__init__: function (__all__) {
					var __name__ = 'org.transcrypt.__base__';
					var __Envir__ = __class__ ('__Envir__', [object], {
						__module__: __name__,
						__init__: function () {
							var self = this;
							self.interpreter_name = 'python';
							self.transpiler_name = 'transcrypt';
							self.transpiler_version = '3.6.91';
							self.target_subdir = '__javascript__';
						}
					});
					var __envir__ = __Envir__ ();
					__pragma__ ('<all>')
						__all__.__Envir__ = __Envir__;
						__all__.__envir__ = __envir__;
						__all__.__name__ = __name__;
					__pragma__ ('</all>')
				}
			}
		}
```

Thanks

**Comment by JdeH** [comment] 2018-01-30 15:16
Right!!
Don't use this switch globally for now, it's flawed, probably has to go.
Only locally as a pragma with simple methods.

**Comment by neriusmika** [comment] 2018-01-30 15:51
I made modifications to visit_FunctionDef in my fork. Global jc switch is working now (but it may cause problems if used improperly).

**Comment by JdeH** [comment] 2018-01-30 15:54
Yes. I know your opinion is it's dangerous. Maybe you're right and it should go. Not sure yet.

**Comment by neriusmika** [comment] 2018-01-30 16:00
Actually the only problem there is "this" scope. When jscall is enabled you can't reassign instance methods like:
```python
mymethod = someinstance.mymethod
mymethod() <= exception here
```
but there is workaround:
```python
mymethod = someinstance.mymethod.bind(someinstance)
mymethod()
```

**Comment by neriusmika** [comment] 2018-01-30 16:14
@JdeH, anyway I recommend to take visit_FunctionDef code from my fork, there are some fixes and simplifications.

**Comment by JdeH** [comment] 2018-01-30 18:15
I'll try to solve these problems in a few separate steps, concentrating on one thing at a time.
Some problems are caused by the JavaScript comment stripper.
Will now first improve that.
If the most obvious things are repaired, I will take a good look at your visit_FunctionDef.
Always very nice if things can be simpler, in the long run that's a matter of survival!

**Comment by neriusmika** [comment] 2018-01-30 18:20
Thanks, it's simpler and clearer and tested with my code and automatic tests.

**Comment by neriusmika** [comment] 2018-01-30 18:30
Jacques, I profiled one my slow function and seems that str on integers where the slowest part, after changing str implementation to this, my function run 3 times faster:
```javascript
    function str (stringable) {
        if (typeof stringable === 'number')
            return stringable.toString();
        else {
            try {
                return stringable.__str__ ();
            }
            catch (exception) {
                try {
                    return repr (stringable);
                }
                catch (exception) {
                    return String (stringable); // No new, so no permanent String object but a primitive in a temporary 'just in time' wrapper
                }
            }
        }
    };
```

**Comment by JdeH** [comment] 2018-01-30 18:57
Very good!
Will first look at your improved visit_FunctionDef

**Comment by JdeH** [comment] 2018-01-30 19:52
@neriusmika 

I am manually merging your and my fixes, which will take some time, during which I probably better not accept PR's.

**Comment by neriusmika** [comment] 2018-01-30 19:53
Ok.

**Comment by JdeH** [comment] 2018-01-30 20:14
Hi @neriusmika 

I have merged,  shipment_test'ed and  committed/uploaded everything except the ongoing work on the collections.
Not an operation to do without full concentration.
Let me know if I made mistakes in the process.
I will also do further testing myself.

Kind regards
Jacques

**Comment by neriusmika** [comment] 2018-01-30 20:16
Thanks, I'll check the differences.

**Comment by JdeH** [comment] 2018-01-30 20:17
BTW I don't know how you feel about it, but I find this close cooperation at a distance fascinating...

**Comment by neriusmika** [comment] 2018-01-30 20:22
Yes, I agree. And because I have quite large app for testing, this helps too. Today I made loading heavy pages 2-3 times faster. I'm happy now :) And short pragmas made the code more readable.

**Comment by JdeH** [comment] 2018-01-30 20:29
I haven't yet looked into this faster pageloads.
Will do so asap, very curious.
BTW tests all work fine.
Will close this issue and its neighbour.

**Comment by JdeH** [comment] 2018-01-30 20:29
Fixed and committed.

**Closed by JdeH** 2018-01-30 20:29 UTC
Labels: IS: bug

**Comment by JdeH** [comment] 2018-01-30 20:32
Thanks @bradiso for reporting this!

**Comment by neriusmika** [comment] 2018-01-30 20:44
Jacques, about == vs ===. When comparing with undefined:
null == undefined // true
null === undefined // false
and maybe there are some other strange cases, you know javascript comparisons are confusing. So I don't know which operator to use, but === is more predictable.

**Comment by JdeH** [comment] 2018-01-30 20:56
I see!
I have to let sink in the consequences of this overnight...

**Comment by JdeH** [comment] 2018-01-30 21:10
@neriusmika 

Have looked at the `str` improvement.
Am I right that your pages have lots of numbers in them?

Given the difference in page load speed, we should indeed adapt the str function.
Only it is a shame that `repr` doesn't benefit from the improvement.

I am still contemplating about a way to make them both faster while avoiding code dupplication.
BTW I am OK with using your version of `str`, at least until we find a solution that also benefits `repr`.
And one or two lines of code dupplication aren't the end of the world.
What I don't know if there are more type conversions to string that might benefit.
Weird that try-catch has such a huge overhead.

If you have ideas on tackling both repr and str in a clever way let me know.
Otherwise we just adapt str for now and get back to this later, as said, I am alright with that, given the remarkable improvement in page load speed in your code.
Still I am curious what exactly is the bottleneck here.

**Comment by neriusmika** [comment] 2018-01-30 21:22
Yes, seems that my components internally uses str(somenumber) in loops. So the performance improvement was significant. Repr is used less, but I must admit that it's slow too. For example my calendar component rendering time was about 25ms, now it's 5ms.
