### ISSUE TITLE
-xt error

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#463] opened 2018-01-30 14:48 UTC
Hi,

Transpiled error (whatever Python source) since 3.6.86+

   **__all__.pow = __pow__;
        }
    };**

```
    var __pow__ = function (a, b) {
        if (typeof a == 'object' && '__pow__' in a) {
            return a.__pow__ (b);
        }
        else if (typeof b == 'object' && '__rpow__' in b) {
            return b.__rpow__ (a);
        }
        else {
            return Math.pow (a, b);
        }
    };

    __all__.pow = __pow__;
         }
     };

    __all__.__getitem__ = __getitem__;
    var __setitem__ = function (container, key, value) {
        if (typeof container == 'object' && '__setitem__' in container) {
            container.__setitem__ (key, value);
        }
        else if ((typeof container == 'string' || container instanceof Array) && key < 0) {
            container [container.length + key] = value;
        }
        else {
            container [key] = value;
        }
    };
```

Thanks

**Comment by JdeH** [comment] 2018-01-30 15:20
No source at all?
Should work  (but obviously doesn't)
Will look into this a.s.a.p.
Thanks!

**Comment by neriusmika** [comment] 2018-01-30 15:21
There was some strange modifications in builtin. In my fork I fixed them, maybe this error is relative.

**Comment by JdeH** [comment] 2018-01-30 15:23
I will first look into your fix.
May have broken something, sorry...

**Comment by JdeH** [comment] 2018-01-30 15:53
Indeed strange things happened to builtin, must have been when I worked on the negative indices.
Will repair it (and spend some thinking on test coverage...)

**Comment by JdeH** [comment] 2018-01-30 18:18
Found the cause of this, interaction between -xt and javascript comment stripper.
Will first attempt to fix this.

**Comment by JdeH** [comment] 2018-01-30 18:52
Fixed, not yet committed.
Will first look at #464 and @neriusmika improved visit_FunctionDef.

**Comment by JdeH** [comment] 2018-01-30 20:30
Committed.
Will close now.
Feel free to reopen in case of remaining problems.

**Comment by JdeH** [comment] 2018-01-30 20:31
Thanks @bradiso for a very productive error report!

**Closed by JdeH** 2018-01-30 20:30 UTC
Labels: IS: bug
